### ISSUE TITLE
h5 编译错误

### ISSUE THREAD

**Issue by FairZhu** [dcloudio/uni-admin#11]
[vite:load-fallback] Could not load D:/HBuilderProjects/小程序后台/store (imported by ..\..\..\HBuilderProjects\小程序后台\js_sdk\uni-admin\error.js): EISDIR: illegal operation on a directory, read
[HBuilder] 16:56:47.665 error during build:
[HBuilder] 16:56:47.666 Error: Could not load D:/HBuilderProjects/小程序后台/store (imported by ..\..\..\HBuilderProjects\小程序后台\js_sdk\uni-admin\error.js): EISDIR: illegal operation on a directory, read
[HBuilder] 16:56:47.672 项目 '小程序后台' 发布h5失败.

**Comment by hbcui1984** [comment]
检查一下磁盘文件是否存在，以及是否有权限问题。
