### ISSUE TITLE
登录页面输入密码的右边那个小眼睛图标出不来，检查发现是css有问题

### ISSUE THREAD

**Issue by zzcaism** [dcloudio/uni-admin#12]
使用的时候，发现登录页面的密码框图标出不来，找到错误并修复如下：
- 错误的点：“\common\uni.css” 里面.uni-icon-password-eye 类的font-family: uniicons; 
- 修正：这个应该是font-family: uni-icons;

**Comment by qq370725567** [comment]
font-family: uniicons; 是正确的
