### ISSUE TITLE
echarts is not defined

### ISSUE THREAD

**Issue by MellowCo** [dcloudio/uni-admin#14]
![image](https://user-images.githubusercontent.com/47939250/176114024-2529a661-5ca9-46f7-807a-547b005db3cf.png)
## 出现原因
* 使用 `https://xxxxx/tongji/index.html` 访问页面时，会将`index.html`拼接到url中导致js加载错误
![image](https://user-images.githubusercontent.com/47939250/176114426-bfd016b5-0802-4935-9620-44d4c34b329c.png)

* 代码中 js的链接地址
![image](https://user-images.githubusercontent.com/47939250/176114711-f9afb027-4d3e-4dd5-9d88-6619923348ce.png)

* 在浏览器中 使用`https://xxxxx/tongji/index.html`访问 尾部的`html`也被拼接进去了
![image](https://user-images.githubusercontent.com/47939250/176115032-0c0c444a-b696-4385-a583-4049f4be32f0.png)

* 使用 `https://xxxxx/tongji/` 访问则正常
![image](https://user-images.githubusercontent.com/47939250/176115487-22732730-e80c-4e01-9b4a-c41f4fb6ed17.png)

**Comment by qq370725567** [comment]
试试新版还有问题不
