### ISSUE TITLE
文件查找失败：'@dcloudio/uni-stacktracey' at pages/uni-stat/error/js/js.vue:193

### ISSUE THREAD

**Issue by jibinlonga** [dcloudio/uni-admin#18]
文件查找失败：'@dcloudio/uni-stacktracey' at pages/uni-stat/error/js/js.vue:193

**Comment by jibinlonga** [comment]
@dcloudio/uni-stacktracey这个包搜都搜不到，怎么装？

**Comment by StrivingRabbit** [comment]
升级 HBuilderX 到 3.5.3+
