### ISSUE TITLE
1.10.1版本存在的问题

### ISSUE THREAD

**Issue by a516117636** [dcloudio/uni-admin#24]
1.阿里云空间，运行云服务空间初始化向导，报错：

> 公共模块上传失败。失败原因：云函数 DCloud-clientDB 依赖的公共模块 uni-id 不存在或未上传到云端。

> 云函数uni-portal上传失败。失败原因：获取公共模块 uni-id 云端代码文件失败。。

2.请升级uni id pages到最新版，当前版本太低，有些功能无法实现
3.uni-admin和uni-id-pages中uni-id-users.schema.json不一样，请统一

**Comment by chenruilong** [comment]
问题已修复，请更新至 uni-admin 2.0
