### ISSUE TITLE
使用邮箱验证码注册后在登录页面登录报错

### ISSUE THREAD

**Issue by a516117636** [dcloudio/uni-admin#25]
控制台返回结果：{"errCode":"uni-id-invalid-username","errMsg":"用户名不合法"}
注册账号时使用的页面路径：/uni_modules/uni-id-pages/pages/register/register-by-email
登录时使用的页面路径：/pages/login/login

**Comment by a516117636** [comment]
是不是因为登录时判断错了，以为是用的username+密码登录，实际上用的是邮箱+密码登录

**Comment by chenruilong** [comment]
已修复，请升级至最新版本。
