### ISSUE TITLE
初始化 uni-admin 竟然都跑不起来的吗？

### ISSUE THREAD

**Issue by theshying** [dcloudio/uni-admin#29]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/18634059/199943108-e69fc9b6-c37f-4ef6-a8e2-0b83c8ebceb1.png">

HBuilder X: 3.5.3.20220729

uni-admin:  2.1.3

直接通过 HBuilder 初始化的项目 uni-admin  都跑步起来，你们版本发布都这么随意的？
都不自测一下？

**Comment by Wangyaqi** [comment]
此问题已在HBuilderX 3.5.5修复
