### ISSUE TITLE
刷新页面后无法调用hasRole判断角色

### ISSUE THREAD

**Issue by cc4dogman** [dcloudio/uni-admin#6]
如题，登录成功后如果在刷新页面App.vue会去调用init方法去后端请求用户数据，待初始化完成后才能获取对应登录用户的信息，但此时页面已经渲染完成，前端需要提前判断角色去过滤数据，能不能等初始化完成后再去渲染整体页面啊？

**Comment by hbcui1984** [comment]
角色权限等敏感信息，应该是在云端判断，前端判断是不安全的。
理论上，你在schema中配置好权限，uni-admin请求时会自动带上用户身份，由clientDB模块在云端自动判断权限。

**Comment by hbcui1984** [comment]
角色权限等敏感信息，应该是在云端判断，前端判断是不安全的。
理论上，你在schema中配置好权限，uni-admin请求时会自动带上用户身份，由clientDB模块在云端自动判断权限。
