### ISSUE TITLE
使用uni-admin与uni-starter绑定后database合并问题

### ISSUE THREAD

**Issue by gaixm** [dcloudio/uni-admin#9]
根据unicloud官方视频做admin的项目创建P14，使用uni-admin与uni-starter绑定后，进行移动至关联项目下时出现database合并，此时db_init.json和好几个schema需要合并，里面内容有好多不同，请问该如何合并比较好？
比如，opendb-verify-codes.schema.json，uni-starter中是最新的，uni-admin中是旧的，合并过来会覆盖新的怎么办？

**Comment by hbcui1984** [comment]
老项目的话，以新的覆盖旧的；
后续官方会让不同项目都保持最新版的schema定义。
